### ISSUE TITLE
Android 10, Error: "systemCancel", after entering password or graphic key

### ISSUE THREAD

**Issue by ilya-efimenko** [aparajita/capacitor-biometric-auth#15]
Angular v13, Capacitor v5
Device: Xiaomi redmi 9c, Android 10
Steps to reproduce:
- call BiometricAuth.authenticate({ allowDeviceCredential: true })
- Enter the password or graphic key
- Error appears
[Video Link](https://drive.google.com/file/d/1kXIEM2zWDk26vYzVB37DH0L7ANwquztZ/view?usp=sharing)

**Comment by aparajita** [comment]
Привет. It seems to be a bug in the Xiaomi software, I have no control over what happens once the system authenticate dialog comes up. I have tested on several other brands of Android phones and it's working fine.

**Comment by ilya-efimenko** [comment]
I also reproduced it in Android studio with Pixel 5 API 29 emulator

**Comment by aparajita** [comment]
This is a known bug that only affects some vendor versions of Android, notably Xiaomi Redmi phones:

https://issuetracker.google.com/issues/142740104?pli=1

I really don't feel like spending any time trying to work around it, since no one in that issue thread was completely successful in doing so. You will have to do without device credentials on API < 30.
