### ISSUE TITLE
Question: Does `biometryType` really indicate the primary (most secure) type of biometry supported?

### ISSUE THREAD

**Issue by vadimk7** [aparajita/capacitor-biometric-auth#28]
Hello @aparajita 👋 

Thanks for creating and maintaining this plugin! 

Currently I'm checking what's the best option to implement biometric auth for my Capacitor app and if for iOS everything is clear, then for Android it's not that obvious. Meaning, there could be more than one type availbale and how to handle that properly is the question... 

In the doc mentioned that [CheckBiometryResult](https://github.com/aparajita/capacitor-biometric-auth/tree/main?tab=readme-ov-file#checkbiometryresult) `biometryType` returns the primary (most secure) type of biometry supported by the device, however in the [code ](https://github.com/aparajita/capacitor-biometric-auth/blob/main/android/src/main/java/com/aparajita/capacitor/biometricauth/BiometricAuthNative.java#L144) I see that first element from the collection is taken:
```java
biometryTypes = getDeviceBiometryTypes();
result.put("biometryType", biometryTypes.get(0).getType());
```
And if both `FEATURE_FINGERPRINT` and `FEATURE_FACE` are supported, then `FEATURE_FINGERPRINT` will be returned. @aparajita, is that intentional? 🤔

**Comment by aparajita** [comment]
In my experience Android returns the primary biometry first, that's why I return the first one. On Android there is no way to tell the strength of a particular biometry, so I have to assume the primary biometry is returned first.

As for how to handle multiple types of biometry, take a look at the demo app, I deal with it there. You can, for example, specify that you only want the plugin to return strong biometry.

**Comment by vadimk7** [comment]
Thank you!
