### ISSUE TITLE
Check if plugin is available

### ISSUE THREAD

**Issue by ms-emp** [aparajita/capacitor-biometric-auth#39]
I have a Capacitor app where the JavaScript bundle may be a later version than the native layer. 

I am trying to check if the plugin is available before using it. I tried `Capacitor.isPluginAvailable('BiometricAuthNative')`, but this returns true even when the plugin is not implemented in the native layer. Additionally, I attempted to call `BiometricAuth.checkBiometry` within a `try/catch` block, but the app freezes when trying to invoke a function on the plugin if it is not implemented on the native side.

**Comment by aparajita** [comment]
> I have a Capacitor app where the JavaScript bundle may be a later version than the native layer.

I'm not clear on what this means. Do you mean a newer version of Capacitor running against a version of the plugin meant for an earlier version of Capacitor?

**Comment by ms-emp** [comment]
I'm using [Capgo](https://capgo.app/) to ensure the JavaScript is always updated to the latest version, regardless of the app's native version.

**Comment by aparajita** [comment]
When you say "the app's native version", what exactly does that mean?

**Comment by ms-emp** [comment]
If we introduce biometric login in version 2 of the app, users who are still on version 1 will still be using the updated JavaScript. This is possible because we can push an update to the JavaScript bundle without requiring a native app update.

**Comment by aparajita** [comment]
Ah, now I understand. If you are adding a native plugin to an app, you can't use Capgo, because the native code must be updated in addition to the Javascript. If you add the Javascript for a plugin without the native code, the plugin is essentially broken and Capacitor is bound to be confused, and any attempt to execute a native call will fail horribly. This is a Capacitor issue, not specific to my plugin.

`Capacitor.isPluginAvailable` only checks if the plugin has been registered in the JS layer.

I don't know of any built in way to check if the native code for a plugin exists, you might try asking on the Ionic forum.
